# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapchatClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseCore'
pod 'FirebaseStorage'
pod 'SDWebImage'
pod 'ImageSlideshow', '~> 1.9'
pod "ImageSlideshow/Kingfisher"



  # Pods for SnapchatClone

end
